project:
  type: website
  output-dir: docs


execute:
  freeze: auto  # re-render only when source changes
  warning: false
  message: false

website:
  title: "Obesity UK vs Australian corpus comparison"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Analysis
        menu:
          - text: "Analysis"
            href: 400_analysis/ConditionAndPersonFirst.qmd
    right:
      - about.qmd
  repo-url: https://github.com/Sydney-Informatics-Hub/
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  page-footer:
    center: "Copyright 2022, Darya Vanichkina, Sydney Informatics Hub"

about:
  template: solana

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly
    toc-depth: 2
    code-link: true
    code-fold: true
    crossref:
      fig-title: Figure
      tbl-title: Table


