---
title: "PIPE-XXX: PROJECT TITLE"
author: "Authors"
date: "dd/mm/yyyy"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Project details

- Clients: X, Y, Z
- Faculty: X
- School: ?
- Research centre: ?
- Collaborators and their affilications: ?

## Project scoping details
- Scope prepared by X
- Scope prepared on
- Project manager 


### Researcher Availability

- Who is the active person helping?
- How available are they to participate in this study?


## 2. Project summary

### Research context

This research aims to:

1. X
2. B

### Client needs

- A
- B
- C

### Current data
- X



## 3. Project Implementation

### Project plan

1. What needs to be done?
2. What's the timeline for each step?


### Scheduling

- Any notes? 

### Deliverables

1. A
2. B
3. C

### SIH skills required

- Python/R/SQL?
- XXX
- yyyy

### In scope

### Out of scope
- More than X weeks FTE work


### Acceptance Criteria

- x

### Handover plan

- X

## 4. Project Evaluation

### SIH Benefits (Summary)

- X/

### Cost (FTE weeks)
- X weeks FTE

***

SIH staff will fill out the below

***

## 5. Essential criteria

 | |
|:------ | :------ |
Sydney Researcher | Y: 
Clear project statement | Y
Data quality | Y
Solvable | Y 
Domain Expert | Y
Planned | Y
Strategic Plan | Y
Data Science | Y
Priority | Y: Health
Deliverables | Y
Infrastructure | Y

## 6. Value and Impact

### Drives the success of larger groups, larger collaborations or high-profile projects.

- Score: X/10
- Details:
    - Name of Research Group/Centre: 
    - Name of Collaboration: 


### Publications that are high-impact - foundational, highly cited, with potential for wider adoption of methods and knock-on outcomes.

- Score: X/10
1. Target Journal: Nature (Impact Factor 40000)
- Name of Authors: Amazing researcher,  (name of SIH data analyst?)
- Proposed Paper Title: How to write a Science paper in 5 days.



### Potential for patents, start-ups, open-source code, policy influence.

- Policy influence X/10



### Develop funding opportunities for the university and/or SIH, such as large CoE-scale grants and further involvement with successful and well funded groups.

- Score: X/10
- Name of Grant Application: 
- Date of Proposed Submission: 

### Total score

X/40 (refer to Rubric for scoring guide)

## 7. KPI

 | |
|:------ | :------ |
Papers SIH Coauthors (*measure only, not KPI) | N
Number of Papers: Papers SIH Acknowledged | Y - Number of Papers: 1000
Collaborators who publish | Name: Amazing Researcher
Collaborators who have grants | Name: Amazing Researcher
Grant applications created | Y: 
Grants project supporting | Name of Grant:
Software released for public use | Y/N: TBA
New Clients | Y
KPI Score | ?/6

